### ISSUE TITLE
User not authorized to perform the action

### ISSUE THREAD

**Issue by innayatullah** [aws-containers/demo-app-for-docker-compose#4]
I'm getting the error while applying the changeset
"User is not authorized to perform that action on the specified resource Service:Efs"

I've tried to give the permissions to DescribeNetworkInterfaceGroups to both the user in CLI as well as the ExtractBuildRole inside ComposeRolePolicy but without any luck.
Can you guys help me out in this.
 
![image](https://user-images.githubusercontent.com/17039498/151805968-39ca8a98-a1c6-471d-a701-811205e88d01.png)

**Comment by innayatullah** [comment]
This happens when I've added the Volumes in my docker-compose file. I was able to deploy the stacks without the volume specification and the demo application worked fine. However I have a use case where I need to provide the EFS

**Comment by gentksb** [comment]
This is maybe temporary problem.
I met the same error at the same date, but I can run every template in succeed today.

My CloudTrail log recorded this error as "unknown error".

```
    "errorCode": "AccessDenied",
    "errorMessage": "An unknown error occurred",
```

**Comment by ollypom** [comment]
Hi @innayatullah , thank you for reporting the issue. I've just gone through the blog [walk through ](https://aws.amazon.com/blogs/containers/automated-software-delivery-using-docker-compose-and-amazon-ecs/) again and I am not able to recreate this error.

If you are following through the blog, the permissions that Compose needs to stand up the sample application can be found [here](https://github.com/aws-containers/demo-app-for-docker-compose/blob/875c45f3beff5dee23a0de49c0f28ffab94c3684/pipeline/cloudformation.yaml#L240). If you need to add additional permissions to stand up the stack, this is where you should do it (not in the role that a CLI user uses when running `aws cloudformation create-stack`)

Do you mind sharing the compose file you are trying to deploy?

**Comment by frinzekt** [comment]
I am also experiencing the same issue
![Screen Shot 2022-02-23 at 3 23 17 pm](https://user-images.githubusercontent.com/44391389/155276334-2700595e-3af8-4456-8f3c-e98b66691d9a.png)

i didnt touch any of the config, just simply run the tutorial to see how it is all working together.
Here's the compose file I am trying to deploy (basically the exact same thing)

```yml
x-aws-vpc: ${AWS_VPC}
x-aws-cluster: ${AWS_ECS_CLUSTER}
x-aws-loadbalancer: ${AWS_ELB}

services:
  frontend:
    image: ${IMAGE_URI:-frontend}:${IMAGE_TAG:-latest}
    build: ./frontend
    environment:
      REDIS_URL: "backend"
    networks:
      - demoapp
    ports:
      - 80:80

  backend:
    image: public.ecr.aws/docker/library/redis:6.2
    volumes:
      - redisdata:/data
    networks:
      - demoapp

volumes:
  redisdata:

networks:
  demoapp:

```

I have tried rerunning the pipeline by doing
```bash
aws s3 cp compose-bundle.zip s3://$BUCKET_NAME/compose-bundle.zip
```

but no luck... it fails at the same place
